name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        id: pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Debug check file
        run: |
          ls -lah
          ls -lah dist || true

      - name: Move file to dist
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/ || echo "No file generated"

      - name: Push pacman-contribution-graph.svg to the output branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
